# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "0.0.0-next"
dockers:
  - image_templates:
    - ghcr.io/nfowl/quilkin-controller:{{ .Tag }}-amd64
    - nfowl/quilkin-controller:{{ .Tag }}-amd64
    use: buildx
    dockerfile: images/Dockerfile
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--platform=linux/amd64"
  - image_templates:
    - ghcr.io/nfowl/quilkin-controller:{{ .Tag }}-arm64
    - nfowl/quilkin-controller:{{ .Tag }}-arm64
    use: buildx
    dockerfile: images/Dockerfile
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--platform=linux/arm64"
  - image_templates:
    - ghcr.io/nfowl/quilkin-controller:{{ .Tag }}-arm
    - nfowl/quilkin-controller:{{ .Tag }}-arm
    use: buildx
    dockerfile: images/Dockerfile
    goos: linux
    goarch: arm
    goarm: 7
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--platform=linux/arm/v7"
docker_manifests:
  - name_template: ghcr.io/nfowl/quilkin-controller:{{ .Tag }}
    image_templates:
      - ghcr.io/nfowl/quilkin-controller:{{ .Tag }}-amd64
      - ghcr.io/nfowl/quilkin-controller:{{ .Tag }}-arm64
      - ghcr.io/nfowl/quilkin-controller:{{ .Tag }}-arm
  - name_template: nfowl/quilkin-controller:{{ .Tag }}
    image_templates:
      - nfowl/quilkin-controller:{{ .Tag }}-amd64
      - nfowl/quilkin-controller:{{ .Tag }}-arm64
      - nfowl/quilkin-controller:{{ .Tag }}-arm
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
