apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: quilkin-controller
build:
  local:
    useBuildkit: true
  artifacts:
  - image: ghcr.io/nfowl/quilkin-controller
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
    - name: quilkin-controller
      chartPath: charts/quilkin-controller
      artifactOverrides:
        controller.image: ghcr.io/nfowl/quilkin-controller # no tag present!
      imageStrategy:
        helm: {}