apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: quilkin-controller
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quilkin-controller
  namespace: system
  labels:
    app: quilkin-controller
    control-plane: quilkin-controller
spec:
  selector:
    matchLabels:
      control-plane: quilkin-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: quilkin-controller
        control-plane: quilkin-controller
        nfowler.dev/quilkin: "disabled"
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /quilkin-controller
        args:
        - --leader-elect
        image: ghcr.io/nfowl/quilkin-controller:latest
        name: manager
        ports:
          - containerPort: 18000
            name: grpc-xds
          - containerPort: 9443
            name: https-admission
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
          - name: temp
            mountPath: /tmp
      volumes:
        - name: temp
          emptyDir: {}
      serviceAccountName: quilkin-controller
      terminationGracePeriodSeconds: 10

