apiVersion: v1
kind: Namespace
metadata:
  name: quilkin-testing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  sender-test2
  namespace: quilkin-testing
spec:
  selector:
    matchLabels:
      app:  sender-test2
  template:
    metadata:
      annotations:
        "nfowler.dev/quilkin.sender": "proxy"
      labels:
        app:  sender-test2
    spec:
      containers:
      - name: samplepod
        command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
        image: alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
