apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "quilkin-controller.name" $ }}-leader-election
  labels:
    app: {{ template "quilkin-controller.name" $ }}
{{- include "quilkin-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "quilkin-controller.name" $ }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "quilkin-controller.serviceAccountName" . }}
  namespace: {{ template "quilkin-controller.namespace" . }}
