apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "quilkin-controller.fullname" . }}
  labels:
    app: {{ template "quilkin-controller.name" $ }}
{{- include "quilkin-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "quilkin-controller.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "quilkin-controller.serviceAccountName" . }}
  namespace: {{ template "quilkin-controller.namespace" . }}
