apiVersion: v1
kind: Service
metadata:
  name: {{ include "quilkin-controller.fullname" . }}
  namespace: {{ template "quilkin-controller.namespace" . }}
  labels:
    {{- include "quilkin-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https-admission
      protocol: TCP
      name: https-admission
  selector:
    {{- include "quilkin-controller.selectorLabels" . | nindent 4 }}
