{{- if .Values.controller.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quilkin-controller.serviceAccountName" . }}
  namespace: {{ template "quilkin-controller.namespace" . }}
  labels:
    {{- include "quilkin-controller.labels" . | nindent 4 }}
  {{- with .Values.controller.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
