apiVersion: v1
kind: Service
metadata:
  name: {{ template "quilkin-controller.fullname" . }}
  namespace: {{ template "quilkin-controller.namespace" . }}
  labels:
    {{- include "quilkin-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controller.service.type }}
  ports:
    - port: {{ .Values.controller.service.webhookPort }}
      targetPort: https-admission
      protocol: TCP
      name: https-admission
    - port: {{ .Values.controller.service.xdsPort }}
      targetPort: grpc-xds
      protocol: TCP
      name: grpc-xds
    - port: {{ .Values.controller.service.metricsPort }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "quilkin-controller.selectorLabels" . | nindent 4 }}
