# Prometheus Monitor Service (Metrics)
{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: quilkin-controller
    {{- include "quilkin-controller.labels" . | nindent 4 }}
  name: {{ include "quilkin-controller.fullname" . }}
  namespace: {{ template "quilkin-controller.namespace" . }}
spec:
  endpoints:
    - path: /metrics
      port: http-metrics
      scheme: http
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      control-plane: quilkin-controller
{{- end }}
